Feature/profile
peaksoft-school/task-tracker-js9 pull request #14
Opened 2023-07-13 10:05 UTC by aliSuper06

2023-07-13 12:43 UTC, airises approved these changes

2023-07-14 09:13 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/d9992ff8-caf6-4e6a-b518-5abd6fe781cf)
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/ff7728f3-4140-4e89-827c-301372100b16)
смотри разницу и исправь

2023-07-14 09:15 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/de079911-da4d-4bd9-9d15-72bcaa10ae39)
сделай так чтобы можно было менять фото профиля, желательно используй библиотеку react-dropzone и ещё исправь кнопку edit

2023-07-14 09:17 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/07055df2-5f60-4415-92dd-d454b56bf636)
сделай валидации на эти инпуты

2023-07-14 09:18 UTC, AziatAbd commented
я не вижу имени рядом с фото

2023-07-14 09:24 UTC, AziatAbd commented
app.js тоже очисти

2023-07-14 11:35 UTC, AziatAbd requested changes

2023-07-14 11:35 UTC, AziatAbd commented on src/components/profile/Profile.jsx
> +   })
если используешь react-hook-form то состояния для инпутов не нужны. посмотри видосы или почитай документацию как её использовать, а то в инпутах я ничего не могу писать

2023-07-17 03:13 UTC, AziatAbd requested changes

2023-07-17 03:13 UTC, AziatAbd commented on src/components/profile/Profile.jsx
> +   })
это состояние не нужна если ты используешь react-hook-form

2023-07-17 03:14 UTC, AziatAbd commented
почитай как использовать react-hook-form

2023-07-17 03:16 UTC, AziatAbd commented
App.js тоже очисти

2023-07-18 12:19 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/cb47f6ab-36f2-43db-a04c-bf24babd1fe2)
если что-то нажимаю то выходит такая ошибка

2023-07-18 12:19 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/ca237cf9-5c20-4778-b065-cad726711970)
сделай цифру белым

2023-07-18 13:36 UTC, merged