created Input
peaksoft-school/task-tracker-js9 pull request #16
Opened 2023-07-14 07:36 UTC by airises

2023-07-15 05:49 UTC, ZhakshylykNasip approved these changes

2023-07-15 09:12 UTC, AziatAbd requested changes

2023-07-15 09:12 UTC, AziatAbd commented on src/components/UI/input/Input.jsx
> +}) {
добавьте ref

2023-07-15 09:26 UTC, AziatAbd requested changes

2023-07-15 09:26 UTC, AziatAbd commented on src/components/UI/input/Input.jsx
> +   const ref = useRef()
он должен приходить из пропса

2023-07-15 10:01 UTC, AziatAbd requested changes

2023-07-15 10:01 UTC, AziatAbd commented on src/components/UI/input/Input.jsx
> +   ref,
ref не будет работать без forwardRef'a

2023-07-17 03:30 UTC, AziatAbd requested changes

2023-07-17 03:30 UTC, AziatAbd commented on src/components/UI/comments/CommentsSection.jsx
что он здесь делает?

2023-07-17 08:34 UTC, merged