Feature/photo color
peaksoft-school/task-tracker-js9 pull request #18
Opened 2023-07-16 05:54 UTC by aliSuper06

2023-07-16 06:02 UTC, airises approved these changes

2023-07-17 03:28 UTC, AziatAbd requested changes

2023-07-17 03:28 UTC, AziatAbd commented on src/components/photoColor/Color.jsx
> +                  <BoardBlock board={board} />
если я нажму на один свет то он должен вернуть мне этот свет

2023-07-17 03:28 UTC, AziatAbd commented on src/components/photoColor/Color.jsx
> +            <ExitIcon />
иконки должны быть внутри iconButton. через пропс должны приходить функции для них

2023-07-17 03:28 UTC, AziatAbd commented on src/components/photoColor/Photo.jsx
> +      </AllBoard>
тоже самое

2023-07-17 03:28 UTC, AziatAbd commented on src/App.js
> +         <Photos boards={photos} />
очисти

2023-07-18 11:47 UTC, AziatAbd requested changes

2023-07-18 11:47 UTC, AziatAbd commented on src/components/photoColor/Color.jsx
> +                  </BoardBlock>
iconButton не нужен. Нужно чтобы возвращал когда я нажимал на BoardBlock

2023-07-18 11:47 UTC, AziatAbd commented on src/components/photoColor/Photo.jsx
> +      </AllBoard>
здесь тоже сделай чтобы он возвращал фотку

2023-07-18 11:47 UTC, AziatAbd commented on src/components/photoColor/Color.jsx
> +                     <IconButton onClick={() => handleColorClick(board.color)}>
ещё board.color возвращает undefined

2023-07-18 11:47 UTC, AziatAbd commented on src/components/photoColor/Color.jsx
> +            </IconButton>
для left и exit нужны функции которые придут через пропс

2023-07-18 14:06 UTC, AziatAbd requested changes

2023-07-18 14:06 UTC, AziatAbd commented on src/components/photoColor/Color.jsx
> +            </IconButton>
где функции?

2023-07-19 04:39 UTC, merged