created favourite
peaksoft-school/task-tracker-js9 pull request #24
Opened 2023-07-20 11:26 UTC by aliSuper06

2023-07-20 11:31 UTC, airises approved these changes

2023-07-20 13:10 UTC, ZhakshylykNasip approved these changes

2023-07-21 04:28 UTC, AziatAbd requested changes

2023-07-21 04:28 UTC, AziatAbd commented on src/components/favourite/Favourite.jsx
> +         {favouriteData.map((item) => (
сделай проверку на массив, если он пустой пусть покажет какой-нибудь текст если нет, то данные

2023-07-21 04:28 UTC, AziatAbd commented on src/components/favourite/Favourite.jsx
> +               </TextContainer>
если я нажму на карточку пусть она вернёт id этой карточки

2023-07-21 04:30 UTC, AziatAbd commented
можешь ещё добавить чтобы при ховере карточка становилась сероватая что-то типа такого

2023-07-21 13:14 UTC, AziatAbd requested changes

2023-07-21 13:14 UTC, AziatAbd commented on src/components/favourite/Favourite.jsx
> +            <p>Массив пусто</p>
напиши какое-нибудь красивое слово а не это

2023-07-22 10:04 UTC, merged