Feature/sidebar
peaksoft-school/task-tracker-js9 pull request #27
Opened 2023-07-20 12:30 UTC by ZhypargulKanybekova

2023-07-20 12:45 UTC, alixandr00 approved these changes

2023-07-20 13:41 UTC, ZhakshylykNasip approved these changes

2023-07-21 06:12 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/94de85fe-3870-43cf-8fb2-54e95347a0d7)

2023-07-21 06:12 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/5aad7c94-c10d-4bfa-ac8e-afec576b29f5)
иконка плюса куда-то уехала

2023-07-21 06:13 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/fcb9da1c-fda9-46be-96cf-564ea1a3a0ef)
если нажать на settings то должна появиться такая модалка

2023-07-21 06:14 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/204e62f0-70ba-4c1d-9f13-eefad022bc51)
добавьте им хотя-бы cursor pointer, чтобы было заметно что можно на неё нажать

2023-07-21 06:16 UTC, AziatAbd requested changes

2023-07-21 06:16 UTC, AziatAbd commented on src/components/sidebar/SideHead.jsx
> +                        <LeftIcon fill="3C3C3C" />
если нажать на стрелку sidebar должна закрываться

2023-07-22 11:06 UTC, AziatAbd requested changes

2023-07-22 11:06 UTC, AziatAbd commented on src/utils/helpers/Helpers.jsx
> +]
переместите это в general

2023-07-22 11:39 UTC, ZhypargulKanybekova commented
general ал кайсыл жакта?

сб, 22 июл. 2023 г. в 17:06, Aziat ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/utils/helpers/Helpers.jsx
> <https://github.com/peaksoft-school/task-tracker-js9/pull/27#discussion_r1271282551>
> :
>
> > +export const data = [
> +   {
> +      name: 'Taigan',
> +      partisipants: 222,
> +      issues: 30,
> +      id: 1,
> +   },
> +]
> +
> +export const workspacedata = [
> +   {
> +      name: 'LMS',
> +      partisipants: 222,
> +      issues: 30,
> +      id: 2,
> +   },
> +   {
> +      name: 'Accounting',
> +      partisipants: 222,
> +      issues: 30,
> +      id: 3,
> +   },
> +   {
> +      name: 'LMS',
> +      partisipants: 222,
> +      issues: 30,
> +      id: 4,
> +   },
> +   {
> +      name: 'Accounting',
> +      partisipants: 222,
> +      issues: 30,
> +      id: 5,
> +   },
> +]
>
> переместите это в general
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/peaksoft-school/task-tracker-js9/pull/27#pullrequestreview-1542082113>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7D5JQKOE2TUNPT5BHAVNMLXROX27ANCNFSM6AAAAAA2RLI6M4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-25 04:08 UTC, AziatAbd approved these changes

2023-07-25 04:08 UTC, merged