created assignee
peaksoft-school/task-tracker-js9 pull request #36
Opened 2023-08-02 14:22 UTC by airises

created assignee section

2023-08-03 06:06 UTC, ZhakshylykNasip approved these changes

2023-08-03 13:14 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/fbe09e4c-e9de-47ed-94a6-4d983f270298)

2023-08-03 13:14 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/a05997b9-80cc-4d2d-b105-96b4fb877087)
где аватарки?

2023-08-03 13:20 UTC, AziatAbd requested changes

2023-08-03 13:20 UTC, AziatAbd commented on src/components/UI/assignee/AssigneeSection.jsx
> +                     />
если я нажму на checkbox то он должен вернуть id этого user'a

2023-08-03 13:20 UTC, AziatAbd commented on src/components/UI/assignee/AssigneeSection.jsx
> +                  </AssigneeMapContainer>
измените цвет при hover'e

2023-08-03 13:24 UTC, AziatAbd requested changes

2023-08-03 13:24 UTC, AziatAbd commented on src/components/UI/assignee/AssigneeSection.jsx
> +export const AssigneeSection = () => {
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/af5422e5-d008-4858-9cf6-ee7d88a1eae8)

это не просто компонента а select

2023-08-04 03:57 UTC, AziatAbd approved these changes

2023-08-04 03:57 UTC, merged