Favorite interegation
peaksoft-school/task-tracker-js9 pull request #44
Opened 2023-08-10 10:23 UTC by NurzhanovBekzat

2023-08-15 06:40 UTC, ZhypargulKanybekova approved these changes

2023-08-15 08:52 UTC, AziatAbd requested changes

2023-08-15 08:52 UTC, AziatAbd commented on src/components/favourite/Favourite.jsx
> +   console.log('favorites: ', favorite)
удалите все console'ки

2023-08-15 08:52 UTC, AziatAbd commented on src/config/axiosInstance.js
> +      'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2OTE3MTk4NjcsImlhdCI6MTY5MTY1OTg2NywidXNlcm5hbWUiOiJhZG1pbkBnbWFpbC5jb20ifQ.nY5IXZkQ0Gpg9-kSsOQQHlULKVsxMmAAXHK7GzzFEBc'
он не нужен, у вас уже работают sign-in/sign-up

2023-08-15 08:54 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/45999b8b-0471-4a28-b50e-9e81b082b119)

соедините роуты чтобы когда нажал на favorites, открылась модалка

2023-08-17 09:47 UTC, AziatAbd requested changes

2023-08-17 09:47 UTC, AziatAbd commented on src/components/favourite/Favourite.jsx
> +               onClick={() => handleStarClickBoard(item.boardId)}
уберите эту функцию, если нажать на неё то должно перекинуть в этот workspace

2023-08-17 09:47 UTC, AziatAbd commented on src/components/header/Header.jsx
> +                           </ModalUi>
модалка должна закрываться когда произойдёт клик в backdrop

2023-08-17 09:47 UTC, AziatAbd commented on src/config/axiosFileInstance.js
> +   const { token } = store.getState().login.accessToken
у вас вместо login слайса auth

2023-08-17 09:47 UTC, AziatAbd commented on src/config/axiosInstance.js
> +   const token = store.getState().login.accessToken
тоже самое

2023-08-23 04:35 UTC, merged