Feature/crud comments
peaksoft-school/task-tracker-js9 pull request #53
Opened 2023-08-25 11:52 UTC by airises

2023-08-26 08:45 UTC, ZhakshylykNasip approved these changes

2023-08-28 06:27 UTC, AziatAbd requested changes

2023-08-28 06:27 UTC, AziatAbd commented on src/components/UI/comments/comments-part/CommentsMap.jsx
> +export const CommentsMap = React.memo(
что я говорил на счёт имени файла

2023-08-28 06:27 UTC, AziatAbd commented on src/store/auth/authSlice.js
> +            console.log('actions: ', actions)
все console.log() удаляем

2023-08-28 06:27 UTC, AziatAbd commented on src/components/profile/Profile.jsx
> +      if (state.edit !== null) {
сделайте state?.edit

2023-08-28 06:27 UTC, AziatAbd commented on src/components/profile/Profile.jsx
> +                        : getItemById?.lastName}
здесь тоже

2023-08-28 06:27 UTC, AziatAbd commented
добавьте commentsSlice в index.js

2023-08-30 04:53 UTC, merged