Feature/attachment
peaksoft-school/task-tracker-js9 pull request #57
Opened 2023-08-29 03:22 UTC by Amirbek02

2023-08-29 09:18 UTC, ZhakshylykNasip approved these changes

2023-08-29 09:23 UTC, airises approved these changes

2023-08-30 04:41 UTC, AziatAbd requested changes

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +   console.log(photoLink)
все console.log удаляем

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +   }, [])
для dispatch'a не нужно использовать async await. В одной функции нельзя вызывать два dispatch'a

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +   }, [])
используйте dispatch внутри createAsyncThunk. try catch тоже не нужна

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +            AttachmentPos({
функции открывать с маленькой буквой

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +            AttachmentPos({
и правильно писать

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +               cardId: 28,
если card готов передайте её id а не статичную

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +               ))}
если images пустая пусть вместо пустоты будет какой-нибудь текст

2023-08-30 04:41 UTC, AziatAbd commented on src/components/attachment/Attachment.jsx
> +            </div>
она должна была быть кнопкой

2023-08-30 04:41 UTC, AziatAbd commented on src/components/innerCard/InnerCard.jsx
> +   const openDoor = () => {
openDoor?

2023-08-30 04:41 UTC, AziatAbd commented on src/config/axiosFileInstance.js
> +   const { token } = store.getState().login.accessToken
у вас токен лежит в auth.token

2023-08-30 08:40 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/task-tracker-js9/assets/115453436/ea7e9308-3201-49e3-9872-1cc90b9c02ab)
что это?

2023-08-31 03:35 UTC, merged